// src/app/models/district.model.ts

export interface State {
  id?: number;           // Optional because it's auto-generated
  sName: string;
  sCode: string;
  SAbb: string;
  IsActive?: string;   // Optional, defaults to true

  IState_rpt_Heading: string;   // Optional, defaults to true

  CreateUser?: string;  // Optional, can be set by backend
  CreateDate?: Date;    // Optional, should be generated by backend
  ChangeUser?: string;  // Optional, can be set by backend
  ChangeDate?: Date;    // Optional, should be updated by backend
}
